version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: logibridge-db
    restart: always
    environment:
      POSTGRES_DB: logibridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: logibridge-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logibridge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AUTH_JWT_SECRET: secret123
      AUTH_JWT_EXPIRATION: 900000
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres_data: