# =========================
# DATABASE CONFIG
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/logibridge?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=dev_user
spring.datasource.password=Dev@2026#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# JWT CONFIG
# =========================
auth.jwt.secret=ZmFrZV9zZWNyZXRfZm9yX2Rldl9vbmx5X2RvX25vdF91c2VfaW5fcHJvZA==
auth.jwt.expiration=900000