spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

auth.jwt.secret=${AUTH_JWT_SECRET}
auth.jwt.expiration=${AUTH_JWT_EXPIRATION}

spring.h2.console.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=true